export const REPO_URL = 'https://github.com/Raivali/panel'
export const ORGANIZATION_URL = 'https://github.com/Raivali'
export const DONATION_URL = 'https://donate.raivali.org'
export const DISCUSSION_GROUP = 'https://t.me/Pasar_Guard'
export const DOCUMENTATION = 'https://docs.raivali.org'
